openapi: 3.0.1
info:
  title: Cards API
  version: "1.0"
  description: API для работы с карточками

#servers:
#  - url: 192.168.49.113:8080

paths:
  /api/v1/get-all-cards-paginated:
    get:
      summary: Получить список карточек с пагинацией
      tags:
        - Cards
      description: Возвращает список карточек с учетом параметров страницы и лимита
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: Номер страницы (начиная с 1)
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Количество элементов на странице
      responses:
        '200':
          description: Успешный ответ со списком карточек
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 13
                        ownerId:
                          type: integer
                          example: 12
                        cardTitle:
                          type: string
                          example: cardTitle 17
                        cardDescription:
                          type: string
                          example: cardDescription 17
                        cardDate:
                          type: string
                          format: date
                          example: 2025-08-08
                        isVerified:
                          type: boolean
                          example: false
                  page:
                    type: integer
                    example: 2
                  limit:
                    type: integer
                    example: 10
                  total:
                    type: integer
                    example: 14
  /api/v1/get-all-cards:
    get:
      summary: Получить все карточки
      tags:
        - Cards
      responses:
        '200':
          description: Список карточек
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CardModel'
      security:
        - bearerAuth: [ ]

  /api/v1/create-card:
    post:
      summary: Создать новую карточку
      tags:
        - Cards
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCardRequest'
      responses:
        '200':
          description: Успешное создание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
      security:
        - bearerAuth: [ ]
  /api/v1/signup:
    post:
      summary: Регистрация нового пользователя
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Успешная регистрация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          description: Неверные данные
        '409':
          description: Конфликт (например, пользователь уже существует)

  /api/v1/login:
    post:
      summary: Авторизация пользователя
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          description: Неверный логин или пароль
        '409':
          description: Конфликт
  /api/v1/update-card:
    post:
      summary: Обновить карточку
      tags:
        - Cards
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCardRequest'
      responses:
        '200':
          description: Карточка успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          description: Отсутствуют обязательные поля
        '409':
          description: Конфликт при обновлении
      security:
        - bearerAuth: []
  /api/v1/delete-card:
    delete:
      summary: Удалить карточку по ID
      tags:
        - Cards
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
          description: ID карточки для удаления
      responses:
        '200':
          description: Карточка успешно удалена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResponse'
        '400':
          description: Не передан ID
        '409':
          description: Конфликт при удалении
      security:
        - bearerAuth: []

  /api/v1/get-user-info:
    get:
      summary: Получить информацию о текущем пользователе
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserModel'
        '400':
          description: Пользователь не найден
        '401':
          description: Неавторизован


components:
  securitySchemes:
    bearerAuth:
     type: http
     scheme: bearer
     bearerFormat: JWT
  schemas:
    AddCardRequest:
      type: object
      required:
        - cardTitle
        - cardDescription
        - cardDate
        - isVerified
      properties:
        id:
          type: integer
          nullable: true
        cardTitle:
          type: string
        cardDescription:
          type: string
        cardDate:
          type: string
        isVerified:
          type: boolean

    RegisterRequest:
      type: object
      required:
        - email
        - login
        - password
        - firstname
        - lastname
        - role
      properties:
        email:
          type: string
        login:
          type: string
        password:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        role:
          type: string

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string

    UserModel:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        login:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        role:
          type: string

    BaseResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    CardModel:
      type: object
      properties:
        id:
          type: integer
        ownerId:
          type: integer
        cardTitle:
          type: string
        cardDescription:
          type: string
        cardDate:
          type: string
        isVerified:
          type: boolean




