version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_POSTGRES_URL: "jdbc:postgresql://db:5432/cardsdb"
      DB_POSTGRES_USER: "postgres"
      DB_POSTGRES_PASSWORD: "1598753"
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cardsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1598753
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
